language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '8'
script:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/